#!/bin/bash
echo "=== Testing Duplicate Quotation Feature ==="
echo ""
echo "Feature Implementation Summary:"
echo "================================"
echo ""
echo "1. Backend API Route (POST /api/income/quotation/[id])"
echo "   - Added duplicate endpoint in /src/app/api/income/quotation/[id]/route.ts"
echo "   - Fetches original quotation with all related data"
echo "   - Creates new quotation with 'Draft' status"
echo "   - Generates unique quotation number (QT-{timestamp})"
echo "   - Copies all categories, items, and pricing information"
echo "   - Resets document status to 'Draft' for new quotation"
echo ""
echo "2. Frontend Components Updated:"
echo "   - /src/components/quotation/ActionButtons.tsx"
echo "     * Added FileCopy icon for duplicate action"
echo "     * Added onDuplicate callback prop"
echo "     * Duplicate button placed first (priority action)"
echo "     * Color: green (success)"
echo ""
echo "   - /src/components/forms/quotation/QuotationsTable.tsx"
echo "     * Added handleDuplicate function"
echo "     * POST request to duplicate endpoint"
echo "     * Auto-refreshes table after successful duplication"
echo "     * Increased action column width from 150 to 180px"
echo ""
echo "3. Duplicate Behavior:"
echo "   - Creates exact copy of original quotation"
echo "   - New quotation starts in 'Draft' status"
echo "   - Copies all pricing settings (VAT, tax, discounts)"
echo "   - Links to same customer/contactor references"
echo "   - Copies all categories and line items"
echo "   - Document details note shows source quotation"
echo ""
echo "4. API Usage:"
echo "   POST /api/income/quotation/{id}"
echo "   Body: { \"duplicateType\": \"full\" }"
echo ""
echo "================================"
echo "Feature implementation complete!"
echo "================================"
